{{- if .Values.ingressBackoffice.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  name: backoffice
spec:
  rules:
  - host: backoffice-helm.docker.internal
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: "backoffice"
            port:
              number: 8080

{{- end }}